name: il_app
description: 
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  go_router: ^14.6.0
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.3.3

  il_core:
    path: ../il_core

  il_basic_auth:
    path: ../il_basic_auth

  il_ws:
    path: ../il_ws

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
