name: il_app
description: 
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.6.0

  il_core:
    path: ../il_core

  il_basic_auth:
    path: ../il_basic_auth

  il_entities:
    path: ../il_entities

  il_ws:
    path: ../il_ws

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
