name: il_display_assets_map
description:
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_svg: ^2.0.16
  vector_math: ^2.1.4
  font_awesome_flutter: ^10.8.0

  il_core:
    path: ../../il_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
