name: il_core
description: Core package
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.20.1
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
