name: il_ws
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

  http: ^1.2.2
  multicast_dns: ^0.3.2+7

  il_core:
    path: ../il_core

  il_entities:
    path: ../il_entities

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
