name: il_ws
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:

  http: ^1.2.2
  mqtt_client: ^10.5.0

  path: ^1.9.0
  path_provider: ^2.1.5

  il_core:
    path: ../il_core

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
